package me.imvc.app.entities;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

/**
 * Authorities generated by hbm2java
 */
public class Authorities implements java.io.Serializable {

	private Long id;
	private Roles roles;
	private Users users;
	private String username;
	private String authority;

	public Authorities() {
	}

	public Authorities(Roles roles, Users users, String username,
			String authority) {
		this.roles = roles;
		this.users = users;
		this.username = username;
		this.authority = authority;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

}
