package me.imvc.app.entities;

// Generated 2013-12-6 10:15:25 by Hibernate Tools 3.4.0.CR1

/**
 * Config generated by hbm2java
 */
public class Config implements java.io.Serializable {

	private Long id;
	private String name;
	private String value;

	public Config() {
	}

	public Config(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
