package me.imvc.app.entities;

import java.math.BigDecimal;
import java.util.Date;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class EarnRate implements java.io.Serializable {

	private Long id;
	private Double efrom;
	private Double eend;
	private Integer sort;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Double getEfrom() {
		return efrom;
	}
	public void setEfrom(Double efrom) {
		this.efrom = efrom;
	}
	public Double getEend() {
		return eend;
	}
	public void setEend(Double eend) {
		this.eend = eend;
	}
	public Integer getSort() {
		return sort;
	}
	public void setSort(Integer sort) {
		this.sort = sort;
	}
}
