package me.imvc.app.entities;

import java.math.BigDecimal;
import java.util.Date;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Flow implements java.io.Serializable {

	private Long id;
	private Member member;
	private Integer type;
	private Integer money;
	private String tocard;
	private String fromcard;
	private String tobank;
	private String frombank;
	private Integer dirction;
	private Date ts;
	private String remark;
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Member getMember() {
		return this.member;
	}
	public void setMember(Member member) {
		this.member = member;
	}
	public Integer getType() {
		return this.type;
	}
	public void setType(Integer type) {
		this.type = type;
	}
	public Integer getMoney() {
		return this.money;
	}
	public void setMoney(Integer money) {
		this.money = money;
	}
	public String getTocard() {
		return this.tocard;
	}
	public void setTocard(String tocard) {
		this.tocard = tocard;
	}
	public String getFromcard() {
		return this.fromcard;
	}
	public void setFromcard(String fromcard) {
		this.fromcard = fromcard;
	}
	public String getTobank() {
		return this.tobank;
	}
	public void setTobank(String tobank) {
		this.tobank = tobank;
	}
	public String getFrombank() {
		return this.frombank;
	}
	public void setFrombank(String frombank) {
		this.frombank = frombank;
	}
	public Integer getDirction() {
		return this.dirction;
	}
	public void setDirction(Integer dirction) {
		this.dirction = dirction;
	}
	public Date getTs() {
		return this.ts;
	}
	public void setTs(Date ts) {
		this.ts = ts;
	}
	public String getRemark() {
		return this.remark;
	}
	public void setRemark(String remark) {
		this.remark = remark;
	}
	
}
