package me.imvc.app.entities;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Notices generated by hbm2java
 */
public class Notices implements java.io.Serializable {

	private Long id;
	private String title;
	private String description;
	private String author;
	private String content;
	private String files;
	private Date timeBegin;
	private Date timeEnd;

	public Notices() {
	}

	public Notices(String title, String description, String author,
			String content, String files, Date timeBegin, Date timeEnd) {
		this.title = title;
		this.description = description;
		this.author = author;
		this.content = content;
		this.files = files;
		this.timeBegin = timeBegin;
		this.timeEnd = timeEnd;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public String getFiles() {
		return this.files;
	}

	public void setFiles(String files) {
		this.files = files;
	}

	public Date getTimeBegin() {
		return this.timeBegin;
	}

	public void setTimeBegin(Date timeBegin) {
		this.timeBegin = timeBegin;
	}

	public Date getTimeEnd() {
		return this.timeEnd;
	}

	public void setTimeEnd(Date timeEnd) {
		this.timeEnd = timeEnd;
	}

}
