package me.imvc.app.entities;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Roles generated by hbm2java
 */
public class Roles implements java.io.Serializable {

	private Long id;
	private String code;
	private String name;
	private String remark;
	private Set<Authorities> authoritieses = new HashSet<Authorities>(0);

	public Roles() {
	}

	public Roles(String code) {
		this.code = code;
	}

	public Roles(String code, String name, String remark,
			Set<Authorities> authoritieses) {
		this.code = code;
		this.name = name;
		this.remark = remark;
		this.authoritieses = authoritieses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public Set<Authorities> getAuthoritieses() {
		return this.authoritieses;
	}

	public void setAuthoritieses(Set<Authorities> authoritieses) {
		this.authoritieses = authoritieses;
	}

}
