package me.imvc.app.entities;

import java.math.BigDecimal;
import java.util.Date;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Ssc implements java.io.Serializable {

	private Long id;
	private String no;
	private Integer sum;
	private Integer cross;
	private Date time;
	private Integer times;
	private String qihao;
	private String daxiao;
	private String danshuang;
	private String longhuhe;
	private String qiansan;
	private String zhongsan;
	private String housan;
	private Date stime;
	private Date etime;
	private Integer allwin;
	private Integer income;
	private Integer rate;

	public Ssc() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public Integer getSum() {
		return sum;
	}

	public void setSum(Integer sum) {
		this.sum = sum;
	}

	public Integer getCross() {
		return cross;
	}

	public void setCross(Integer cross) {
		this.cross = cross;
	}

	public Date getTime() {
		return time;
	}

	public void setTime(Date time) {
		this.time = time;
	}

	public Integer getTimes() {
		return times;
	}

	public void setTimes(Integer times) {
		this.times = times;
	}

	public String getQihao() {
		return qihao;
	}

	public void setQihao(String qihao) {
		this.qihao = qihao;
	}

	public String getDaxiao() {
		return daxiao;
	}

	public void setDaxiao(String daxiao) {
		this.daxiao = daxiao;
	}

	public String getDanshuang() {
		return danshuang;
	}

	public void setDanshuang(String danshuang) {
		this.danshuang = danshuang;
	}

	public String getLonghuhe() {
		return longhuhe;
	}

	public void setLonghuhe(String longhuhe) {
		this.longhuhe = longhuhe;
	}

	public String getQiansan() {
		return qiansan;
	}

	public void setQiansan(String qiansan) {
		this.qiansan = qiansan;
	}

	public String getZhongsan() {
		return zhongsan;
	}

	public void setZhongsan(String zhongsan) {
		this.zhongsan = zhongsan;
	}

	public String getHousan() {
		return housan;
	}

	public void setHousan(String housan) {
		this.housan = housan;
	}

	public Date getStime() {
		return stime;
	}

	public void setStime(Date stime) {
		this.stime = stime;
	}

	public Date getEtime() {
		return etime;
	}

	public void setEtime(Date etime) {
		this.etime = etime;
	}

	public Integer getAllwin() {
		return allwin;
	}

	public void setAllwin(Integer allwin) {
		this.allwin = allwin;
	}

	public Integer getIncome() {
		return income;
	}

	public void setIncome(Integer income) {
		this.income = income;
	}

	public Integer getRate() {
		return rate;
	}

	public void setRate(Integer rate) {
		this.rate = rate;
	}

}
