package me.imvc.app.entities;

import java.math.BigDecimal;
import java.util.Date;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Sscorder implements java.io.Serializable {

	private Long id;
	private Integer pos;
	private Integer num;
	private Member member;
	private Date otime;
	private Integer money;
	private Integer emoney;
	private Integer iswin;
	private Ssc ssc;
	private String qihao;
	private String detail;
	
	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	public Integer getPos() {
		return pos;
	}
	public void setPos(Integer pos) {
		this.pos = pos;
	}
	public Integer getNum() {
		return num;
	}
	public void setNum(Integer num) {
		this.num = num;
	}
	public Member getMember() {
		return member;
	}
	public void setMember(Member member) {
		this.member = member;
	}
	public Date getOtime() {
		return otime;
	}
	public void setOtime(Date otime) {
		this.otime = otime;
	}
	public Integer getMoney() {
		return money;
	}
	public void setMoney(Integer money) {
		this.money = money;
	}
	public Integer getEmoney() {
		return emoney;
	}
	public void setEmoney(Integer emoney) {
		this.emoney = emoney;
	}
	public Integer getIswin() {
		return iswin;
	}
	public void setIswin(Integer iswin) {
		this.iswin = iswin;
	}
	public Ssc getSsc() {
		return ssc;
	}
	public void setSsc(Ssc ssc) {
		this.ssc = ssc;
	}
	public String getQihao() {
		return qihao;
	}
	public void setQihao(String qihao) {
		this.qihao = qihao;
	}
	public String getDetail() {
		return detail;
	}
	public void setDetail(String detail) {
		this.detail = detail;
	}
	
}
