package me.imvc.app.entities;

// Generated 2013-11-23 17:08:22 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * UserExtends generated by hbm2java
 */
public class UserExtends implements java.io.Serializable {

	private Long id;
	private String name;
	private Integer age;
	private String sex;
	private String tel;
	private String mtel;
	private Set<Users> userses = new HashSet<Users>(0);

	public UserExtends() {
	}

	public UserExtends(String name, Integer age, String sex, String tel,
			String mtel, Set<Users> userses) {
		this.name = name;
		this.age = age;
		this.sex = sex;
		this.tel = tel;
		this.mtel = mtel;
		this.userses = userses;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getAge() {
		return this.age;
	}

	public void setAge(Integer age) {
		this.age = age;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getTel() {
		return this.tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getMtel() {
		return this.mtel;
	}

	public void setMtel(String mtel) {
		this.mtel = mtel;
	}

	public Set<Users> getUserses() {
		return this.userses;
	}

	public void setUserses(Set<Users> userses) {
		this.userses = userses;
	}

}
